import math
from typing import List, Dict, Any, Optional
import json
import os
import re

from langchain_core.tools import tool
from pydantic import SecretStr
from langchain_groq import ChatGroq
from langchain_core.messages import HumanMessage

from database_tools import (
    get_conn,
    fetch_user_topics,
    fetch_user_goals,
    fetch_topic_mastery,
)

def _fetch_user_topics(conn, user_id: str) -> List[Dict[str, Any]]:
    return fetch_user_topics(user_id)


def _fetch_user_goals(conn, user_id: str) -> List[str]:
    return fetch_user_goals(user_id)


def _fetch_topic_mastery(conn, topic_id: int, user_id: str):
    return fetch_topic_mastery(user_id, topic_id)


def _weakness_topics(conn, user_id: str, max_recs: int = 5) -> List[Dict[str, Any]]:
    user_topics = _fetch_user_topics(conn, user_id)
    weakest = sorted(user_topics, key=lambda x: x.get("mastery", 0.0))[:max_recs]
    out: List[Dict[str, Any]] = []
    for t in weakest:
        metrics = {
            "mastery": t.get("mastery", 0.0), 
            "confidence": t.get("confidence", 0.0), 
            "interest": t.get("interest", 0.5)
        }
        out.append({
            "topic_id": t.get("topic_id"),
            "name": t.get("name"),
            "score": round(1.0 - t.get("mastery", 0.0), 3),
            "metrics": metrics,
            "reasons": ["weakness: low mastery"],
        })
    return out


def _safe_extract_json(raw_content: str) -> str:
    """Safely extracts JSON payload from potential markdown code fences."""
    content = raw_content.strip()
    if "```json" in content:
        content = content.split("```json", 1)[1].split("```", 1)[0].strip()
    elif "```" in content:
        content = content.split("```", 1)[1].split("```", 1)[0].strip()
    return content.strip("`").strip()


def _resilient_json_parse(raw_content: str) -> List[Dict[str, Any]]:
    """Attempts regular JSON loading, falling back to regex object recovery if truncated."""
    cleaned = _safe_extract_json(raw_content)
    try:
        return json.loads(cleaned)
    except Exception:
        # Regex fallback: Find valid looking JSON objects {"name": ..., "reason": ...}
        extracted = []
        matches = re.findall(r'\{\s*"name"\s*:\s*".*?"\s*,\s*"reason"\s*:\s*".*?"\s*\}', cleaned, re.DOTALL)
        for m in matches:
            try:
                extracted.append(json.loads(m))
            except Exception:
                continue
        if extracted:
            return extracted
        raise ValueError("JSON payload could not be recovered structurally.")


@tool
def recommend_topics_for_user(user_id: str, max_recs: int = 5, goal_texts: Optional[List[str]] = None, enable_llm: bool = True) -> Dict[str, Any]:
    """Recommend topics for a user strictly generated by the LLM based on their goals and currently studied topics without pulling from database candidate pools."""
    conn = get_conn()
    recommendations: List[Dict[str, Any]] = []
    try:
        user_topics = _fetch_user_topics(conn, user_id)
        studied_names = ", ".join([str(t.get("name")) for t in user_topics if t.get("name")])

        goals_local: List[str] = goal_texts or []
        if not goals_local:
            try:
                goals_local = _fetch_user_goals(conn, user_id)
            except Exception:
                goals_local = []
        
        joined_goals = "; ".join([g for g in goals_local if g]) if goals_local else "General professional growth"

        if enable_llm:
            prompt = (
                f"You are an advanced curriculum personalization assistant. "
                f"The user has already studied these topics: [{studied_names}]. "
                f"The user's current goals are: '{joined_goals}'.\n\n"
                f"Based strictly on this context, decide and generate a list of up to {max_recs} NEW topic names "
                f"that logically extend their knowledge and align with their goals. "
                f"Do NOT recommend topics already in their studied list, and do NOT use standard internal database topics.\n"
                f"Return ONLY a valid JSON array of strings (e.g., [\"Topic A\", \"Topic B\"]). No explanations, no numbering, no markdown fences."
            )

            llm = ChatGroq(model="llama-3.3-70b-versatile", api_key=SecretStr(os.getenv("GROQ_API_KEY") or ""), temperature=0.2)
            resp = llm.invoke([HumanMessage(content=prompt)])
            cleaned_json = _safe_extract_json(str(resp.content))
            
            gen = json.loads(cleaned_json)
            if isinstance(gen, list):
                for name in gen[:max_recs]:
                    if not isinstance(name, str) or not name.strip():
                        continue
                    recommendations.append({
                        "topic_id": None,
                        "name": name.strip(),
                        "score": 1.0,
                        "metrics": {"mastery": 0.0, "confidence": 0.0, "interest": 0.5},
                        "reasons": ["LLM dynamically suggested to bridge studied topics and goals"]
                    })
    except Exception:
        pass  
    finally:
        try:
            conn.close()
        except Exception:
            pass

    return {"recommendations": recommendations}


# Backwards-compatible alias
recommend_next_topics = recommend_topics_for_user


@tool
def get_weakness_topics(user_id: str, max_recs: int = 5) -> Dict[str, Any]:
    """Expose user's weakest topics as a tool for the API."""
    conn = get_conn()
    try:
        return {"recommendations": _weakness_topics(conn, user_id, max_recs)}
    finally:
        try:
            conn.close()
        except Exception:
            pass


@tool
def generate_roadmap_for_user(
    user_id: str,
    steps: int = 6,
    goal_text: Optional[str] = None,
) -> Dict[str, Any]:
    """Generate a cohesive learning roadmap sticking strictly to the step count. 
    Passes studied topics to the LLM to decide whether the user needs to focus on existing/studied topics or completely new ones.
    """
    conn = get_conn()
    roadmap: List[Dict[str, Any]] = []
    message = ""
    
    # Initialize variables outside the try block to avoid unbound Pylance errors
    target_goal = goal_text or "General Full-Stack & Software Engineering Track"
    raw_goal = target_goal
    studied_map: Dict[str, Dict[str, Any]] = {}

    try:
        try:
            user_topics = _fetch_user_topics(conn, user_id) or []
        except Exception:
            user_topics = []

        # Create an in-memory dictionary of studied topics for O(1) matching case-insensitively
        studied_map = {
            str(t.get("name")).lower().strip(): t 
            for t in user_topics if t.get("name")
        }
        
        studied_names = ", ".join([str(t.get("name")) for t in user_topics if t.get("name")])
        
        # Typos normalization (e.g. "mearn" -> "MERN Stack")
        if "mearn" in target_goal.lower():
            target_goal = re.sub(r'\bmearn\b', 'MERN Stack', target_goal, flags=re.IGNORECASE)

        prompt = (
            f"You are an expert curriculum design agent. The user's roadmap target/prompt is: '{target_goal}'.\n"
            f"The user has previously studied these topics: [{studied_names}].\n\n"
            f"CRITICAL TYPO & AMBIGUITY HANDLING:\n"
            f"- If the target prompt contains a typo, abbreviation, or unrecognized word (e.g., 'mearn'), deduce its logical meaning based on context (e.g., interpret 'mearn stack' as 'MERN Stack').\n"
            f"- If a specific word is completely unrecognizable, do NOT fail. Ignore that specific word and dynamically generate a comprehensive roadmap based on the remaining intelligible text context (e.g., 'stack developer' -> Full-Stack Web Development).\n\n"
            f"YOUR TASK:\n"
            f"Generate a comprehensive learning roadmap consisting of EXACTLY {steps} steps.\n"
            f"Analyze the studied topics relative to the goal. Explicitly decide if the user needs to spend initial roadmap "
            f"steps focusing on/reinforcing relevant topics they already studied, or if they should skip straight to completely new topics.\n\n"
            f"Output strictly a valid JSON array containing exactly {steps} objects, where each object represents a step chronologically.\n"
            f"Each object must have exactly two keys: 'name' (the topic name) and 'reason' (KEEP IT SHORT under 15 words, "
            f"explaining if it is a review step or a new domain expansion).\n\n"
            f"if the LLM cannot generate enough steps, say the user has already studied all relevant topics.\n\n"
            f"Example format:\n"
            f"[\n"
            f"  {{\"name\": \"Topic A\", \"reason\": \"Review step: Deepens previous core knowledge.\"}},\n"
            f"  {{\"name\": \"Topic B\", \"reason\": \"New topic: Introduces architectural paradigms.\"}}\n"
            f"]\n"
            f"Do not include markdown code block syntax or prose text outside the JSON."
        )

        llm = ChatGroq(model="llama-3.3-70b-versatile", api_key=SecretStr(os.getenv("GROQ_API_KEY") or ""), temperature=0.3)
        resp = llm.invoke([HumanMessage(content=prompt)])
        
        # Parse using the resilient extractor
        generated_steps = _resilient_json_parse(str(resp.content))

        if isinstance(generated_steps, list):
            generated_steps = generated_steps[:steps]
            for i, step_data in enumerate(generated_steps, start=1):
                t_name = step_data.get("name", f"Advanced Milestone {i}").strip()
                t_reason = step_data.get("reason", "Progressive milestone toward goal.")
                
                # Dynamic matching to check if this is a topic the user already studied
                matched_topic = studied_map.get(t_name.lower())
                
                if matched_topic:
                    t_id = matched_topic.get("topic_id")
                    mastery_score = matched_topic.get("mastery", 0.0)
                    confidence_score = matched_topic.get("confidence", 0.0)
                    interest_score = matched_topic.get("interest", 0.5)
                    explanation_type = "llm_decision_review"
                else:
                    t_id = None
                    mastery_score = 0.0
                    confidence_score = 0.0
                    interest_score = 0.5
                    explanation_type = "llm_decision_expansion"
                
                roadmap.append({
                    "step": i,
                    "topic_id": t_id,
                    "name": t_name,
                    "reasons": [{"type": explanation_type, "explanation": t_reason}],
                    "metrics": {
                        "mastery": mastery_score, 
                        "confidence": confidence_score, 
                        "interest": interest_score
                    }
                })

        # Dynamic fallback padding using cleanly extracted keywords if LLM under-generated steps
        clean_keyword = target_goal.replace("I want to be a", "").replace("I want to learn", "").strip()
        while len(roadmap) < steps:
            curr_idx = len(roadmap) + 1
            roadmap.append({
                "step": curr_idx,
                "topic_id": None,
                "name": f"{clean_keyword} Phase {curr_idx}",
                "reasons": [{"type": "fallback", "explanation": "Progressive path extension to complete step requirement."}],
                "metrics": {"mastery": 0.0, "confidence": 0.0, "interest": 0.5}
            })
            
        message = f"Successfully generated a personalized {steps}-step roadmap tailored to previous knowledge metrics."

    except Exception as e:
        # Fully dynamic, context-aware layout fallback if LLM or JSON parsing errors out completely
        roadmap = []
        clean_keyword = raw_goal.replace("I want to be a", "").replace("I want to learn", "").strip()
        clean_keyword = re.sub(r'\bmearn\b', 'Full-Stack Web', clean_keyword, flags=re.IGNORECASE)
        
        templates = [
            "Foundations of {k}",
            "Core Logic & Setup in {k}",
            "Intermediate Frameworks of {k}",
            "Data Persistence & State in {k}",
            "Advanced System Architecture for {k}",
            "Security & Optimization in {k}",
            "Real-world Integration of {k}",
            "Production Infrastructure for {k}"
        ]
        
        for i in range(1, steps + 1):
            t_name = templates[(i-1) % len(templates)].format(k=clean_keyword)
            
            # Check if our fallback template name matches an old topic just in case
            matched_topic = studied_map.get(t_name.lower()) if studied_map else None
            
            roadmap.append({
                "step": i,
                "topic_id": matched_topic.get("topic_id") if matched_topic else None,
                "name": t_name,
                "reasons": [{"type": "error_fallback", "explanation": f"Automated structural path sequence for {raw_goal}."}],
                "metrics": {
                    "mastery": matched_topic.get("mastery", 0.0) if matched_topic else 0.0, 
                    "confidence": matched_topic.get("confidence", 0.0) if matched_topic else 0.0, 
                    "interest": 0.5
                }
            })
        message = f"Dynamic fallback sequence applied with historical metric preservation: {str(e)}"
    finally:
        try:
            conn.close()
        except Exception:
            pass

    return {"roadmap": roadmap, "message": message}

# ── BACKWARDS COMPATIBILITY BACKUP HELPERS ────────────────────────────────────

def get_similarity_score(goal_text: str, topic_name: str) -> float:
    """Basic fallback text-matching similarity score engine to prevent external import breakages."""
    if not goal_text or not topic_name:
        return 0.0
    return 1.0 if (topic_name.lower() in goal_text.lower() or goal_text.lower() in topic_name.lower()) else 0.0


def is_goal_relevant(goal_text: str, topic_name: str) -> bool:
    """Basic structural helper method."""
    return get_similarity_score(goal_text, topic_name) > 0.5